config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'folio#index'
  get 'folio/show'
  get 'folio/users'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mastodon_client.rb
class MastodonClient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_oauth(auth)
    user = User.where(provider: auth.provider, email: User.dummy_email(auth)).first
      
    if user != nil then
      user.update!(uid: auth.extra.raw_info.display_name)
    end

    unless user
      user = User.create(
      uid:      auth.extra.raw_info.display_name,
      provider: auth.provider,
      email:    User.dummy_email(auth),
      password: Devise.friendly_token[0, 20],
      token: auth.credentials.token.to_s
      )
      user.save!
    end
    current_user = user
  end
      
  private
      
    def self.dummy_email(auth)
      "#{auth.uid}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/folio_controller.rb
class FolioController < ApplicationController
  before_action :get_info, only: :show

  def index
  end

  def users

    @all_user = User.all

    @users = Hash.new

    @all_user.each do |user|

      user.email.match("@")
      puts $'
      begin 

      client = Mastodon::REST::Client.new(base_url: "https://" + $', bearer_token: user.token)
      puts user.uid
      @users[user.id] = { :account => client.verify_credentials }

      rescue => error
        puts error
      end
    end
  end

  def show
  end

  private

    def get_info
      puts params
        user = User.find(params[:format])

        token = user.token.to_s

        user.email.match("@")
        puts $'

        client = Mastodon::REST::Client.new(base_url: "https://" + $', bearer_token: token)

        id = client.verify_credentials.id

        @toots = client.statuses(id)
        @account = client.verify_credentials
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def mastodon
      callback_from :mastodon
    end
  
    private
  
    def callback_from(provider)
      provider = provider.to_s
  
      @user = User.find_for_oauth(request.env['omniauth.auth'])
  
      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folio_helper.rb
module FolioHelper
end

app/views/folio/index.html.slim
p Mastodon ユーザーフォリオへようこそ！
p ログインすることでこのサービスを使っているMastodonユーザーを検索してフォローすることができます！

- if user_signed_in?
    = link_to("ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-primary")
- else
    = link_to "Mastodonでログイン！", user_mastodon_omniauth_authorize_path, class: "btn btn-primary"

= link_to "ユーザー一覧", folio_users_path, class: "btn btn-primary"

app/views/folio/show.html.slim
    javascript:
        var toots = #{{@toots.to_json}};
        var user = #{{@account.to_json}};
        var url = #{{(@account.url.match('@'))? (@account.url.gsub!('@', 'users/') + '/remote_follow'.to_s).to_json : @account.url.to_json}}
    
    = javascript_pack_tag 'account'
    = javascript_pack_tag 'toot_slide'

app/views/folio/users.html.slim
input#myInput.form-control[type="text" placeholder="Search.."]

table
    thead
        tr
            th
                | アイコン
            th
                | ユーザー名
            th
                | ユーザー情報
            th
                | ステータス

    tbody#myTable
        - @users.each do |key, user|
            tr
                td
                    = link_to image_tag(user[:account].avatar), folio_show_path(key)
                td
                    = User.find(key).uid
                td
                    = user[:account].note.html_safe
                td
                    p = "Toot数 :" +  user[:account].statuses_count.to_s
                    p = " フォロー数 :" + user[:account].following_count.to_s 
                    p =" フォロワー数 :" + user[:account].followers_count.to_s

javascript:
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

app/views/layouts/_header.html.slim
body
  header
    nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
      .container
        a.navbar-brand href="https://mastodon-userfolio.herokuapp.com/" 
          | Mastodonユーザーフォリオ
        button.navbar-toggler aria-controls="navbar" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbar" data-toggle="collapse" type="button" 
          span.navbar-toggler-icon
        #navbar.collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            li.nav-item.dropdown.active
              a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
                | Menu
              .dropdown-menu aria-labelledby="navbarDropdown" 
                = link_to "Home", root_path, class: "dropdown-item"
                = link_to 'About', "", class: "dropdown-item"
                = link_to "Users", folio_users_path, class: "dropdown-item"
                = link_to "Source", "https://github.com/S-H-GAMELINKS/MastodonUserFolio", class: "dropdown-item"
                - if user_signed_in?
                  = link_to("ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item")
                - else
                  = link_to "Mastodonでログイン！", user_mastodon_omniauth_authorize_path, class: "dropdown-item"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | UserFolio
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link[rel="manifest" href="/manifest.json"]
    meta[name="apple-mobile-web-app-capable" content="yes"]
  body

    == render 'layouts/header'

    div[align="center"]
      = yield